AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling Stack with Launch Template and Target Tracking Policy

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
    Default: t2.micro
  AMI:
    Type: AWS::EC2::Image::Id
  AutoScalingGroupName:
    Type: String
    Default: AnishAutoScalingGroup
  miniumumSize:
    Type: Number
    Default: 1
  maximumSize:
    Type: Number
    Default: 2
  desiredCapacity:
    Type: Number
    Default: 1
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AMI
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !ImportValue Anish-SG-ID
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install nginx1 -y
            systemctl start nginx
            systemctl enable nginx
            echo "Welcome to ${AWS::StackName}" > /var/www/html/index.html

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue Anish-Subnet1-ID
        - !ImportValue Anish-Subnet2-ID
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref miniumumSize
      MaxSize: !Ref maximumSize
      DesiredCapacity: !Ref desiredCapacity
      TargetGroupARNs:
        - !ImportValue Anish-TargetGroup-ARN
      Tags:
        - Key: Name
          Value: !Ref AutoScalingGroupName
          PropagateAtLaunch: true

  TargetTrackingScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50.0